name = "hashtag-api"
main = "./workers/index.js"
compatibility_date = "2023-12-01"

[vars]
# 로컬 개발용 환경 변수 (실제 값은 Cloudflare 대시보드에서 설정)
HIKERAPI_KEY = "TgaB9PevFNRmNra0c0FSzWU1UXQfRcII"

[triggers]
crons = []